rgbd_gaze_calibration:
  ros__parameters:
    eyeball_radius:
      min: 0.0105
      max: 0.0135
    sample_consensus:
      distance_threshold: 0.0025
      probability: 0.99
      max_iterations: 1000

    publish_eyelid_pc: true
    publish_markers: true
    use_sim_time: false
