camera:
  ros__parameters:
    serial_no: 950122060455
    base_frame_id: face_d415
    align_depth: false
    enable_pointcloud: false
    dense_pointcloud: true
    color0:
      enabled: true
      resolution: [1920,1080]
      fps: 30
    depth0:
      enabled: true
      resolution: [1280,720]
      fps: 30
    infra1:
      enabled: false
      resolution: [640,480]
      fps: 15
    infra2:
      enabled: false
      resolution: [640,480]
      fps: 15