Pipelines:
- name: ecard
  inputs: [StandardCamera]
  infers:
    - name: FaceDetection
      model: /opt/openvino_toolkit/models/face_detection/output/intel/face-detection-adas-0001/FP16/face-detection-adas-0001.xml
      engine: CPU
      label: /to/be/set/xxx.labels
      batch: 1
      confidence_threshold: 0.5
      enable_roi_constraint: true # set enable_roi_constraint to false if you don't want to make the inferred ROI (region of interest) constrained into the camera frame

    - name: LandmarksDetection
      model: /opt/openvino_toolkit/models/landmarks-regression/output/intel/landmarks-regression-retail-0009/FP16/landmarks-regression-retail-0009.xml
      engine: CPU
      label: to/be/set/xxx.labels
      batch: 1

    - name: HeadPoseEstimation
      model: /opt/openvino_toolkit/models/head-pose-estimation/output/intel/head-pose-estimation-adas-0001/FP16/head-pose-estimation-adas-0001.xml
      engine: CPU
      label: to/be/set/xxx.labels
      batch: 16

  outputs: [ImageWindow, RosTopic, RViz]
  connects:
    - left: StandardCamera
      right: [FaceDetection]

    - left: FaceDetection
      right: [HeadPoseEstimation, LandmarksDetection, ImageWindow, RosTopic, RViz]

    - left: HeadPoseEstimation
      right: [ImageWindow, RosTopic, RViz]

    - left: LandmarksDetection
      right: [ImageWindow, RosTopic, RViz]

Common:
